version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
      - image: selenium/hub
        name: hub
      - image: selenium/node-firefox
        environment:
          HUB_PORT_4444_TCP_ADDR: hub
          HUB_PORT_4444_TCP_PORT: 4444
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-


      - run: npm install
      - run: npm install wdio-mocha-framework
      - run: rm -rf ./node_modues/wdio-mocha-framework
      - run: ls && cd .. && ls 
      - run: npm i --save-dev wdio-mocha-framework@latest

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          command: npm run start
          background: true
        
      # run tests!
      # - run: sudo npm install -g node-gyp
      # - run: /usr/local/bin/node /home/circleci/repo/node_modules/fibers/build
      - run: npm run test

      # - store_artifacts:
      #     path: ./errorShots/
      #     when: always
