version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts-browsers
    working_directory: ~/www
    steps:
      - run: sudo apt-get install apache2
      - run: ls && cd .. && ls
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      #- run:
      #    name: Build app
      #    command: npm run build
      # - run:
      #     name: Start app
      #     command: npm start
      #     background: true
      # - run:
      #     name: Download Selenium
      #     command: cd .. && curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      # - run: cd .. && mkdir selenium-logs
      # - run:
      #     name: Start Selenium
      #     command: cd .. && java -jar selenium-server-standalone-3.5.3.jar -log selenium-logs/selenium.log
      #     background: true
      # run tests!
      #- run: mkdir wdio-v7 && cd wdio-v7 && npm install @wdio/cli
      #- run: ls && cd .. && ls
      #- run: cd wdio-v7 && npx wdio config --yes && npx wdio run ./wdio.conf.js
      - run: npm install @wdio/cli
      - run: ls && cd .. && ls && cd .. && ls
      - run: npx wdio run ./wdio.conf.js
      - run:
          name: Make history dir for allure
          command: mkdir -p allure-results/history
          when: always
      - run:
          name: Download history artfacts
          command: <artifacts.txt xargs -P4 -I % wget %?circle-token=$CIRCLE_TOKEN
          when: always
      # create allure report
      - run: npm run make-report
      - store_artifacts:
          path: ./allure-report/
          when: always
      - store_artifacts:
          path: ./selenium-logs/
          when: always
